---
- name: Playbook to create custom EE
  hosts: workstation-1.fqdn
  # fact gathering is necessary to get date_time info for the tag
  gather_facts: true
  vars_files:
    - common.yml
    - "{{__build}}.yml"

  roles:
    - infra.ee_utilities.ee_builder

  post_tasks:
    - name: Tag image as latest
      containers.podman.podman_tag:
        image: "{{ ee_list[0].name }}:{{ ee_list[0].tag }}"
        target_names:
          - "{{ ee_list[0].name }}:latest"

    - name: Push Image to Nexus
      containers.podman.podman_image:
        name: "{{ ee_list[0].name }}"
        pull: false
        push: true
        username: "{{ username_injector }}"
        password: "{{ password_injector }}"
        executable: "{{ ee_executable | default(omit, true) }}"
        tag: "{{ item }}"
        validate_certs: "{{ ee_validate_certs | default(omit) }}"
        push_args:
          dest: "{{ ee_nexus_registry }}"
      when: ee_image_push
      loop:
        - "{{ ee_list[0].tag | default(omit) }}"
        - "latest"

    - name: Push Image to Automation Hub with latest tag
      containers.podman.podman_image:
        name: "{{ ee_list[0].name }}"
        pull: false
        push: true
        username: "{{ ee_registry_username | default(omit, true) }}"
        password: "{{ ee_registry_password | default(omit, true) }}"
        auth_file: "{{ ee_auth_file | default(omit, true) }}"
        executable: "{{ ee_executable | default(omit, true) }}"
        ca_cert_dir: "{{ ee_ca_cert_dir | default(omit) }}"
        validate_certs: "{{ ee_validate_certs | default(omit) }}"
        tag: latest
        push_args:
          dest: "{{ ee_registry_dest }}"
          sign_by: "{{ ee_sign_by | default(omit) }}"
      when: ee_image_push

    - name: Remove local images
      containers.podman.podman_prune:
        system: true
        system_all: true

- name: Clear out cached images on the controllers
  hosts: controlplane-*
  become: true
  become_user: awx
  tasks:
    - name: Remove local images
      containers.podman.podman_image:
        state: absent
        name: automationhub.fqdn/aap_{{ __build }}_ee
      # We ignore errors because if the image is in use (i.e. another job is running the ee) it will fail
      # A complete clean up is added to the patching job to ensure latest images get pulled
      ignore_errors: true

    - name: Prune any hanging images
      containers.podman.podman_prune:
        system: true
